# Generated by Django 4.1.5 on 2023-02-10 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pet_name', models.CharField(blank=True, max_length=200, null=True)),
                ('Pet_category', models.CharField(blank=True, max_length=200, null=True)),
                ('Pet_Breed', models.CharField(blank=True, max_length=200, null=True)),
                ('Age', models.CharField(blank=True, max_length=200, null=True)),
                ('Pet_photo', models.ImageField(blank=True, null=True, upload_to='vendors')),
                ('user_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
