# Generated by Django 4.1.5 on 2023-02-14 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0002_alter_petprofile_pet_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Patient_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Booking_Date', models.DateField(blank=True, max_length=200, null=True)),
                ('Booking_Time', models.CharField(blank=True, max_length=200, null=True)),
                ('Reason', models.CharField(blank=True, max_length=200, null=True)),
                ('Doctor_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Patient_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pets.petprofile')),
            ],
        ),
    ]
