# Generated by Django 4.1.5 on 2023-02-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
