# Generated by Django 4.1.5 on 2023-02-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_alter_booking_doctor_id_alter_booking_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Doctor_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
