# Generated by Django 4.1.5 on 2023-02-14 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0007_alter_booking_doctor_id_alter_booking_patient_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pet_name', models.CharField(blank=True, max_length=200, null=True)),
                ('Vaccination_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Vaccinated_Date', models.CharField(blank=True, max_length=200, null=True)),
                ('Vaccination_Document', models.ImageField(blank=True, max_length=200, null=True, upload_to='vaccines')),
                ('user_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
