# Generated by Django 4.1.5 on 2023-02-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_vaccination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination',
            name='Vaccination_Document',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='vaccines'),
        ),
    ]
